function conx_contact = conx_contact(in1,in2)
%CONX_CONTACT
%    CONX_CONTACT = CONX_CONTACT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Sep-2021 16:43:11

cone_coeffs1 = in2(1,:);
cone_coeffs2 = in2(2,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
conx_contact = cone_coeffs1.*x4.^2+cone_coeffs2.*x5.^2-x6.^2;
