function conx_contact_x = conx_contact_x(in1,in2)
%CONX_CONTACT_X
%    CONX_CONTACT_X = CONX_CONTACT_X(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Sep-2021 16:43:12

cone_coeffs1 = in2(1,:);
cone_coeffs2 = in2(2,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
conx_contact_x = [0.0,0.0,0.0,cone_coeffs1.*x4.*2.0,cone_coeffs2.*x5.*2.0,x6.*-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
