function conx_plane = conx_plane(in1,in2)
%CONX_PLANE
%    CONX_PLANE = CONX_PLANE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    13-Sep-2021 01:34:43

c1 = in2(1,:);
c2 = in2(2,:);
c3 = in2(3,:);
c4 = in2(4,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
conx_plane = abs(c4+c1.*x1+c2.*x2+c3.*x3).*1.0./sqrt(abs(c1).^2+abs(c2).^2+abs(c3).^2);
