function conx_contact = conx_contact(in1,in2)
%CONX_CONTACT
%    CONX_CONTACT = CONX_CONTACT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Sep-2021 18:12:09

cone_coeffs1 = in2(1,:);
cone_coeffs2 = in2(2,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
conx_contact = -(x5.*7.074550334094646e-1-x6.*7.067583573638259e-1).^2+cone_coeffs1.*x4.^2+cone_coeffs2.*(x5.*7.067583573638259e-1+x6.*7.074550334094646e-1).^2;
