function con = gate_con(in1,in2)
%GATE_CON
%    CON = GATE_CON(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Jul-2021 00:45:00

con = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
