function con_u = motor_con_u(in1,in2,in3)
%MOTOR_CON_U
%    CON_U = MOTOR_CON_U(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Jul-2021 21:21:41

u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
t2 = u2.*7.372881355932203e-2;
t3 = u3.*7.372881355932203e-2;
t4 = u4.*7.372881355932203e-2;
t5 = -t2;
t6 = -t3;
t7 = -t4;
t8 = t4+4.85e+2./5.9e+1;
t10 = t4-4.85e+2./5.9e+1;
t9 = t7+4.85e+2./5.9e+1;
t11 = t7-4.85e+2./5.9e+1;
con_u = reshape([1.0./4.0,1.0./4.0,1.0./4.0,1.0./4.0,-1.0./4.0,-1.0./4.0,-1.0./4.0,-1.0./4.0,t10,t9,t8,t11,t9,t10,t11,t8,t11,t8,t10,t9,t8,t11,t9,t10,t2+t6-2.3e+1,t3+t5-2.3e+1,t2+t3+2.3e+1,t5+t6+2.3e+1,t3+t5+2.3e+1,t2+t6+2.3e+1,t5+t6-2.3e+1,t2+t3-2.3e+1],[8,4]);
