function d = plane_dist_calc(in1,in2)
%PLANE_DIST_CALC
%    D = PLANE_DIST_CALC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Sep-2021 12:51:36

p1_1 = in2(1);
p1_2 = in2(4);
p1_3 = in2(7);
p2_1 = in2(2);
p2_2 = in2(5);
p2_3 = in2(8);
p3_1 = in2(3);
p3_2 = in2(6);
p3_3 = in2(9);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
t2 = -p1_2;
t3 = -p1_3;
t4 = -p2_2;
t5 = -p2_3;
t6 = -p3_2;
t7 = -p3_3;
t8 = p1_1+t2;
t9 = p1_1+t3;
t10 = p2_1+t4;
t11 = p2_1+t5;
t12 = p3_1+t6;
t13 = p3_1+t7;
t14 = t8.*t11;
t15 = t9.*t10;
t16 = t8.*t13;
t17 = t9.*t12;
t18 = t10.*t13;
t19 = t11.*t12;
t20 = -t15;
t21 = -t17;
t22 = -t19;
t23 = t14+t20;
t24 = t16+t21;
t25 = t18+t22;
d = abs(p1_1.*t25-p2_1.*t24+p3_1.*t23-t23.*x3+t24.*x2-t25.*x1).*1.0./sqrt(abs(t23).^2+abs(t24).^2+abs(t25).^2);
