function A = A_calc(in1,b)
%A_CALC
%    A = A_CALC(IN1,B)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Apr-2022 18:16:34

x01 = in1(1,:);
x03 = in1(3,:);
A = reshape([1.0,0.0,cos(x01).*(-3.27e+2./1.0e+3),0.0,1.0,b.*(-2.0./9.0),cos(x03).*(3.0./4.0e+1),sin(x03).*(3.0./4.0e+1),1.0],[3,3]);
