function B = B_calc(in1,b)
%B_CALC
%    B = B_CALC(IN1,B)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Apr-2022 18:16:34

x02 = in1(2,:);
B = [0.0;0.0;x02.*(-2.0./9.0)];
