function df = df_calc(in1)
%DF_CALC
%    DF = DF_CALC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    30-Mar-2022 14:20:31

x01 = in1(1,:);
x02 = in1(2,:);
df = reshape([cos(x01),0.0,1.0,x02./5.0,0.0,1.0./1.0e+1],[2,3]);
