function f = f_calc(in1)
%F_CALC
%    F = F_CALC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    30-Mar-2022 14:20:31

th = in1(3,:);
x01 = in1(1,:);
x02 = in1(2,:);
f = [x02+sin(x01);th./1.0e+1+x02.^2./1.0e+1+1.0];
