function g = g_func(in1,in2,eps1)
%G_FUNC
%    G = G_FUNC(IN1,IN2,EPS1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    01-Oct-2021 00:53:07

p1 = in2(1,:);
p2 = in2(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
g = eps1-sqrt(abs(p1-x1).^2+abs(p2-x2).^2);
