function Jk = Jk_func(in1,in2,in3,in4,in5,in6)
%JK_FUNC
%    JK = JK_FUNC(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Sep-2021 22:25:19

Q1 = in5(1,:);
Q2 = in5(2,:);
Q3 = in5(3,:);
Q4 = in5(4,:);
Q5 = in5(5,:);
Q6 = in5(6,:);
R1 = in6(1,:);
R2 = in6(2,:);
R3 = in6(3,:);
R4 = in6(4,:);
R5 = in6(5,:);
R6 = in6(6,:);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
u5 = in2(5,:);
u6 = in2(6,:);
u_s1 = in4(1,:);
u_s2 = in4(2,:);
u_s3 = in4(3,:);
u_s4 = in4(4,:);
u_s5 = in4(5,:);
u_s6 = in4(6,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x_s1 = in3(1,:);
x_s2 = in3(2,:);
x_s3 = in3(3,:);
x_s4 = in3(4,:);
x_s5 = in3(5,:);
x_s6 = in3(6,:);
Jk = (R1.*(u1-u_s1).^2)./2.0+(R2.*(u2-u_s2).^2)./2.0+(R3.*(u3-u_s3).^2)./2.0+(R4.*(u4-u_s4).^2)./2.0+(R5.*(u5-u_s5).^2)./2.0+(R6.*(u6-u_s6).^2)./2.0+(Q1.*(x1-x_s1).^2)./2.0+(Q2.*(x2-x_s2).^2)./2.0+(Q3.*(x3-x_s3).^2)./2.0+(Q4.*(x4-x_s4).^2)./2.0+(Q5.*(x5-x_s5).^2)./2.0+(Q6.*(x6-x_s6).^2)./2.0;
