function JN = JN_func(in1,in2,in3)
%JN_FUNC
%    JN = JN_FUNC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    30-Sep-2021 22:25:19

Q1 = in3(1,:);
Q2 = in3(2,:);
Q3 = in3(3,:);
Q4 = in3(4,:);
Q5 = in3(5,:);
Q6 = in3(6,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x_s1 = in2(1,:);
x_s2 = in2(2,:);
x_s3 = in2(3,:);
x_s4 = in2(4,:);
x_s5 = in2(5,:);
x_s6 = in2(6,:);
JN = Q1.*(x1./2.0-x_s1./2.0).*(x1-x_s1)+Q2.*(x2./2.0-x_s2./2.0).*(x2-x_s2)+Q3.*(x3./2.0-x_s3./2.0).*(x3-x_s3)+Q4.*(x4./2.0-x_s4./2.0).*(x4-x_s4)+Q5.*(x5./2.0-x_s5./2.0).*(x5-x_s5)+Q6.*(x6./2.0-x_s6./2.0).*(x6-x_s6);
