function x_upd = quad2Dd_func(in1,in2)
%QUAD2DD_FUNC
%    X_UPD = QUAD2DD_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    01-Oct-2021 00:52:56

u1 = in2(1,:);
u2 = in2(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x_upd = [x1+x4./1.0e+1;x2+x5./1.0e+1;x3+x6./1.0e+1;x4-u1.*sin(x3).*(1.0e+1./5.3e+1);x5+u1.*cos(x3).*(1.0e+1./5.3e+1)-9.81e+2./1.0e+3;u2.*(1.25e+2./2.0)+x6];
