function x_upd = x_calc(in1,b)
%X_CALC
%    X_UPD = X_CALC(IN1,B)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Apr-2022 18:16:34

x01 = in1(1,:);
x02 = in1(2,:);
x03 = in1(3,:);
x_upd = [x01+sin(x03).*(3.0./4.0e+1);x02-cos(x03).*(3.0./4.0e+1);x03-sin(x01).*(3.27e+2./1.0e+3)-b.*x02.*(2.0./9.0)];
