function obj_cost_k = obj_cost_k(in1,in2,in3,in4)
%OBJ_COST_K
%    OBJ_COST_K = OBJ_COST_K(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-May-2021 02:12:16

obj_cost_k = 0.0;
