function q_k = q_k_calc(x_bar1)
%Q_K_CALC
%    Q_K = Q_K_CALC(X_BAR1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-May-2021 02:12:17

q_k = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
