function q_N = q_N_calc(in1)
%Q_N_CALC
%    Q_N = Q_N_CALC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-May-2021 02:12:17

x_bar1 = in1(1,:);
x_bar2 = in1(2,:);
x_bar3 = in1(3,:);
x_bar4 = in1(4,:);
x_bar5 = in1(5,:);
x_bar6 = in1(6,:);
x_bar7 = in1(7,:);
x_bar8 = in1(8,:);
x_bar9 = in1(9,:);
x_bar10 = in1(10,:);
q_N = [x_bar1-2.0;x_bar2;x_bar3-1.0;x_bar4;x_bar5;x_bar6;x_bar7-1.0;x_bar8;x_bar9;x_bar10];
