function R_k = R_k_calc(u_bar1)
%R_K_CALC
%    R_K = R_K_CALC(U_BAR1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    02-Jun-2021 21:57:49

R_k = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
