function A = A_calc(in1,in2)
%A_CALC
%    A = A_CALC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    18-Apr-2022 09:30:19

th1 = in2(1,:);
th2 = in2(2,:);
x01 = in1(1,:);
A = reshape([1.0,th2.*cos(x01).*(-4.36e-2),1.0./1.0e+2,th1.*(-2.0./4.5e+1)+1.0],[2,2]);
