function B = B_calc(in1,in2)
%B_CALC
%    B = B_CALC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Apr-2022 19:15:51

x01 = in1(1,:);
x02 = in1(2,:);
B = reshape([0.0,x02.*(-2.0./9.0),0.0,sin(x01).*(-1.09e+2./5.0e+2)],[2,2]);
