function x_upd = x_calc(in1,in2)
%X_CALC
%    X_UPD = X_CALC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Apr-2022 19:15:51

th1 = in2(1,:);
th2 = in2(2,:);
x01 = in1(1,:);
x02 = in1(2,:);
x_upd = [x01+x02./2.0e+1;x02-th1.*x02.*(2.0./9.0)-th2.*sin(x01).*(1.09e+2./5.0e+2)];
