
classdef TrajTransferRequest < ros.Message
    %TrajTransferRequest MATLAB implementation of bridge_px4/TrajTransferRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'bridge_px4/TrajTransferRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '7bec211c9c37912d6558392a02228ea4' % The MD5 Checksum of the message definition
        PropertyList = { 'Hz' 'N' 'UArr' 'XArr' 'LArr' } % List of non-constant message properties
        ROSPropertyList = { 'hz' 'N' 'u_arr' 'x_arr' 'L_arr' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Hz
        N
        UArr
        XArr
        LArr
    end
    methods
        function set.Hz(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TrajTransferRequest', 'Hz');
            obj.Hz = int32(val);
        end
        function set.N(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TrajTransferRequest', 'N');
            obj.N = int32(val);
        end
        function set.UArr(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = single.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'TrajTransferRequest', 'UArr');
            obj.UArr = single(val);
        end
        function set.XArr(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = single.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'TrajTransferRequest', 'XArr');
            obj.XArr = single(val);
        end
        function set.LArr(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = single.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'TrajTransferRequest', 'LArr');
            obj.LArr = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.bridge_px4.TrajTransferRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.bridge_px4.TrajTransferRequest(strObj);
        end
    end
end
