function x_upd = quad_sim(in1,in2,in3,dt)
%QUAD_SIM
%    X_UPD = QUAD_SIM(IN1,IN2,IN3,DT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    18-Mar-2022 12:00:22

Df1_1 = in3(5,:);
Df2_1 = in3(6,:);
Df3_1 = in3(7,:);
Ipp1 = in3(2,:);
Ipp2 = in3(3,:);
Ipp3 = in3(4,:);
m = in3(1,:);
p1 = in1(1,:);
p2 = in1(2,:);
p3 = in1(3,:);
q1 = in1(7,:);
q2 = in1(8,:);
q3 = in1(9,:);
q4 = in1(10,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
w1 = in1(11,:);
w2 = in1(12,:);
w3 = in1(13,:);
wr1 = in2(1,:);
wr2 = in2(2,:);
wr3 = in2(3,:);
wr4 = in2(4,:);
t2 = dt.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = q4.^2;
t7 = w1.^2;
t8 = w2.^2;
t9 = w3.^2;
t10 = 1.0./m;
t11 = t2.*t7;
t12 = t2.*t8;
t13 = t2.*t9;
t14 = t3+t4+t5+t6;
t15 = 1.0./sqrt(t14);
t16 = t11+t12+t13+4.0;
t17 = 1.0./sqrt(t16);
mt1 = [p1+dt.*v1;p2+dt.*v2;p3+dt.*v3;v1+dt.*t10.*(wr1.*(q1.*q3+q2.*q4).*2.0-Df1_1.*v1.^2.*sign(v1));v2-dt.*t10.*(wr1.*(q1.*q2-q3.*q4).*2.0+Df2_1.*v2.^2.*sign(v2));v3-dt.*t10.*(m.*(9.81e+2./1.0e+2)-wr1.*(t3-t4-t5+t6)+Df3_1.*v3.^2.*sign(v3));-t15.*t17.*(q1.*-2.0+dt.*q2.*w1+dt.*q3.*w2+dt.*q4.*w3);t15.*t17.*(q2.*2.0+dt.*q1.*w1+dt.*q3.*w3-dt.*q4.*w2);t15.*t17.*(q3.*2.0+dt.*q1.*w2-dt.*q2.*w3+dt.*q4.*w1);t15.*t17.*(q4.*2.0+dt.*q1.*w3+dt.*q2.*w2-dt.*q3.*w1)];
mt2 = [(Ipp1.*w1+dt.*wr2+Ipp2.*dt.*w2.*w3-Ipp3.*dt.*w2.*w3)./Ipp1;(Ipp2.*w2+dt.*wr3-Ipp1.*dt.*w1.*w3+Ipp3.*dt.*w1.*w3)./Ipp2;(Ipp3.*w3+dt.*wr4+Ipp1.*dt.*w1.*w2-Ipp2.*dt.*w1.*w2)./Ipp3];
x_upd = [mt1;mt2];
