//
//  Academic License - for use in teaching, academic research, and meeting
//  course requirements at degree granting institutions only.  Not for
//  government, commercial, or other organizational use.
//
//  gate_con.cpp
//
//  Code generation for function 'gate_con'
//


// Include files
#include "gate_con.h"
#include "rt_nonfinite.h"

// Function Definitions
void gate_con(const double in1[10], double con[16])
{
  double t10;
  double t11;
  double t12;
  double t13;
  double t14;
  double t15;
  double t16;
  double t17;
  double t18;
  double t19;
  double t6;
  double t7;

  // GATE_CON
  //     CON = GATE_CON(IN1,IN2)
  //     This function was generated by the Symbolic Math Toolbox version 8.6.
  //     14-Jul-2021 21:15:59
  t6 = in1[1] / 20.0;
  t7 = in1[2] / 20.0;
  t10 = in1[6] * in1[7] * 0.00885;
  t11 = in1[6] * in1[8] * 0.00885;
  t12 = in1[6] * in1[9] * 0.00885;
  t13 = in1[7] * in1[8] * 0.00885;
  t14 = in1[7] * in1[9] * 0.00885;
  t15 = in1[8] * in1[9] * 0.00885;
  t16 = in1[6] * in1[6] * 0.004425;
  t17 = in1[7] * in1[7] * 0.004425;
  t18 = in1[8] * in1[8] * 0.004425;
  t19 = in1[9] * in1[9] * 0.004425;
  con[0] = ((-t7 + t11) + -t14) - 0.45;
  con[1] = ((-t7 + t10) + t15) - 0.45;
  con[2] = ((-t7 + t14) + -t11) - 0.45;
  con[3] = ((-t7 + -t10) + -t15) - 0.45;
  con[4] = ((-t6 + -t12) + -t13) - 0.5;
  con[5] = ((((-t6 + t16) + t18) + -t17) + -t19) - 0.5;
  con[6] = ((-t6 + t12) + t13) - 0.5;
  con[7] = ((((-t6 + t17) + t19) + -t16) + -t18) - 0.5;
  con[8] = ((t7 + t14) + -t11) - 0.55;
  con[9] = ((t7 + -t10) + -t15) - 0.55;
  con[10] = ((t7 + t11) + -t14) - 0.55;
  con[11] = ((t7 + t10) + t15) - 0.55;
  con[12] = ((t6 + t12) + t13) - 0.5;
  con[13] = ((((t6 + t17) + t19) + -t16) + -t18) - 0.5;
  con[14] = ((t6 + -t12) + -t13) - 0.5;
  con[15] = ((((t6 + t16) + t18) + -t17) + -t19) - 0.5;
}

// End of code generation (gate_con.cpp)
