function br2wr = br2wr(in1,in2,in3,in4)
%BR2WR
%    BR2WR = BR2WR(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Sep-2021 10:51:12

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
u_p2 = in3(2,:);
u_p3 = in3(3,:);
u_p4 = in3(4,:);
br2wr = [u1.*1.481125e+1;u2./5.0-u_p2./5.0+(u3.*u4)./2.5e+3;u3.*(8.0./2.5e+1)-u_p3.*(8.0./2.5e+1)-(u2.*u4)./1.0e+3;u4.*(2.0./5.0)-u_p4.*(2.0./5.0)+u2.*u3.*6.0e-4];
