function F_m = m2f(in1)
%M2F
%    F_M = M2F(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Aug-2021 18:55:22

wm1 = in1(1,:);
wm2 = in1(2,:);
wm3 = in1(3,:);
wm4 = in1(4,:);
F_m = [wm1.^2.*sign(wm1).*5.86e-6;wm2.^2.*sign(wm2).*5.86e-6;wm3.^2.*sign(wm3).*5.86e-6;wm4.^2.*sign(wm4).*5.86e-6];
