function u_m = w2m(in1)
%W2M
%    U_M = W2M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Aug-2021 18:55:22

wrench1 = in1(1,:);
wrench2 = in1(2,:);
wrench3 = in1(3,:);
wrench4 = in1(4,:);
t2 = wrench1./4.0;
t4 = wrench4.*(2.5e+1./6.0);
t6 = wrench2.*(5.0e+2./1.77e+2);
t7 = wrench3.*(5.0e+2./1.77e+2);
t3 = -t2;
t5 = -t4;
t8 = -t6;
t9 = -t7;
t10 = t3+t4+t6+t7;
t11 = t2+t4+t7+t8;
t12 = t2+t4+t6+t9;
t13 = t2+t5+t6+t7;
u_m = [-sign(t10).*sqrt(abs(t10).*1.706484641638225e+5);sign(t13).*sqrt(abs(t13).*1.706484641638225e+5);sign(t12).*sqrt(abs(t12).*1.706484641638225e+5);sign(t11).*sqrt(abs(t11).*1.706484641638225e+5)];
