function u_m = w2m_est(in1)
%W2M_EST
%    U_M = W2M_EST(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    23-Jul-2021 13:27:15

wrench1 = in1(1,:);
wrench2 = in1(2,:);
wrench3 = in1(3,:);
wrench4 = in1(4,:);
t2 = wrench1.*6.832430541511115e+5;
t3 = wrench2.*1.138738423585186e+7;
t4 = wrench3.*1.138738423585186e+7;
t7 = wrench4.*5.255715801162396e+7;
t5 = -t3;
t6 = -t4;
t8 = -t7;
u_m = [sqrt(t2+t5+t6+t8);sqrt(t2+t3+t4+t8);sqrt(t2+t3+t6+t7);sqrt(t2+t4+t5+t7)];
