function u_m = w2m_est(in1)
%W2M_EST
%    U_M = W2M_EST(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Jul-2021 13:07:26

wrench1 = in1(1,:);
wrench2 = in1(2,:);
wrench3 = in1(3,:);
wrench4 = in1(4,:);
t2 = wrench1.*2.82556115644567e+7;
t3 = wrench4.*2.82556115644567e+8;
t5 = wrench2.*3.192724470560079e+8;
t6 = wrench3.*3.192724470560079e+8;
t4 = -t3;
t7 = -t5;
t8 = -t6;
u_m = [sqrt(t2+t4+t7+t8);sqrt(t2+t4+t5+t6);sqrt(t2+t3+t5+t8);sqrt(t2+t3+t6+t7)];
