function dCn = dCn(in1,in2,in3,in4,in5,in6,trig)
%DCN
%    DCN = DCN(IN1,IN2,IN3,IN4,IN5,IN6,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-Jul-2021 14:19:19

dCn = 0.0;
