function dCN_p = dCN_p(in1,in2,trig)
%DCN_P
%    DCN_P = DCN_P(IN1,IN2,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Jul-2021 17:53:59

x_bar1 = in1(1,:);
x_bar2 = in1(2,:);
x_bar3 = in1(3,:);
x_bar4 = in1(4,:);
x_bar5 = in1(5,:);
x_bar6 = in1(6,:);
x_star1 = in2(1,:);
x_star2 = in2(2,:);
x_star3 = in2(3,:);
x_star4 = in2(4,:);
x_star5 = in2(5,:);
x_star6 = in2(6,:);
dCN_p = trig.*((x_bar1./2.0-x_star1./2.0).*(x_bar1-x_star1)+(x_bar2./2.0-x_star2./2.0).*(x_bar2-x_star2)+(x_bar3./2.0-x_star3./2.0).*(x_bar3-x_star3)+(x_bar4./2.0-x_star4./2.0).*(x_bar4-x_star4)+(x_bar5./2.0-x_star5./2.0).*(x_bar5-x_star5)+(x_bar6./2.0-x_star6./2.0).*(x_bar6-x_star6));
