function dCn_xu = dCn_xu(in1,in2,in3,in4,in5,in6,trig)
%DCN_XU
%    DCN_XU = DCN_XU(IN1,IN2,IN3,IN4,IN5,IN6,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Aug-2021 21:30:41

dCn_xu = 0.0;
