function dCn_u = dCn_u(in1,in2,in3,trig)
%DCN_U
%    DCN_U = DCN_U(IN1,IN2,IN3,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Jul-2021 16:38:46

dCn_u = 0.0;
