function dCn_p = dCn_p(in1,in2,in3,in4,trig)
%DCN_P
%    DCN_P = DCN_P(IN1,IN2,IN3,IN4,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Jul-2021 17:53:58

dCn_p = 0.0;
