function dCn_x = dCn_x(in1,in2,in3,trig)
%DCN_X
%    DCN_X = DCN_X(IN1,IN2,IN3,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Aug-2021 17:00:58

dCn_x = 0.0;
