function dCn_x = dCn_x(in1,in2,in3,trig)
%DCN_X
%    DCN_X = DCN_X(IN1,IN2,IN3,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    23-Jul-2021 13:27:20

dCn_x = 0.0;
