function dCT_xu = dCT_xu(in1,in2,in3,in4,in5,in6,trig)
%DCT_XU
%    DCT_XU = DCT_XU(IN1,IN2,IN3,IN4,IN5,IN6,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Jul-2021 16:38:47

dCT_xu = 0.0;
