function dCT_p = dCT_p(in1,in2,in3,in4,trig)
%DCT_P
%    DCT_P = DCT_P(IN1,IN2,IN3,IN4,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Jul-2021 16:38:47

x_bar1 = in1(1,:);
x_bar2 = in1(2,:);
x_bar3 = in1(3,:);
x_bar4 = in1(4,:);
x_bar5 = in1(5,:);
x_bar6 = in1(6,:);
x_star1 = in3(1,:);
x_star2 = in3(2,:);
x_star3 = in3(3,:);
x_star4 = in3(4,:);
x_star5 = in3(5,:);
x_star6 = in3(6,:);
dCT_p = trig.*((x_bar1./2.0-x_star1./2.0).*(x_bar1-x_star1)+(x_bar2./2.0-x_star2./2.0).*(x_bar2-x_star2)+(x_bar3./2.0-x_star3./2.0).*(x_bar3-x_star3)+(x_bar4./2.0-x_star4./2.0).*(x_bar4-x_star4)+(x_bar5./2.0-x_star5./2.0).*(x_bar5-x_star5)+(x_bar6./2.0-x_star6./2.0).*(x_bar6-x_star6));
