function dCT_u = dCT_u(in1,in2,in3,trig)
%DCT_U
%    DCT_U = DCT_U(IN1,IN2,IN3,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Aug-2021 17:00:59

dCT_u = 0.0;
