function dqn = dqn(in1,in2,trig)
%DQN
%    DQN = DQN(IN1,IN2,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    23-Jul-2021 13:27:20

dqn = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
