function dqn = dqn(in1,in2,trig)
%DQN
%    DQN = DQN(IN1,IN2,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Jul-2021 17:53:58

dqn = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
