function dqn = dqn_calc(in1,in2,trig)
%DQN_CALC
%    DQN = DQN_CALC(IN1,IN2,TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-Jul-2021 14:19:18

dqn = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
