function dRT = dRT(trig)
%DRT
%    DRT = DRT(TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    29-Jul-2021 16:38:46

dRT = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
