function dRT = dRT_calc(trig)
%DRT_CALC
%    DRT = DRT_CALC(TRIG)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-Jul-2021 14:19:18

dRT = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
