function obj_cost_k = obj_cost_k(in1,in2,in3,in4,in5,in6)
%OBJ_COST_K
%    OBJ_COST_K = OBJ_COST_K(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Jul-2021 20:41:59

obj_cost_k = 0.0;
