function q_k = q_k_calc(in1,in2)
%Q_K_CALC
%    Q_K = Q_K_CALC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-Jul-2021 15:08:58

q_k = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
