function R_k = R_k_calc(a)
%R_K_CALC
%    R_K = R_K_CALC(A)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-Jun-2021 20:37:05

R_k = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
