function r_k = r_k_calc(in1,in2,in3)
%R_K_CALC
%    R_K = R_K_CALC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Jul-2021 16:24:28

r_k = [0.0;0.0;0.0;0.0];
