function x_upd = quadcopter_est(in1,in2,in3)
%QUADCOPTER_EST
%    X_UPD = QUADCOPTER_EST(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Sep-2021 10:51:14

F_ext1 = in3(1,:);
F_ext2 = in3(2,:);
F_ext3 = in3(3,:);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
t2 = u2.^2;
t3 = u3.^2;
t4 = u4.^2;
t5 = x7.^2;
t6 = x8.^2;
t7 = x9.^2;
t8 = x10.^2;
t9 = t5+t6+t7+t8;
t10 = t2+t3+t4+1.6e+5;
t11 = 1.0./sqrt(t9);
t12 = 1.0./sqrt(t10);
mt1 = [x1+x4./2.0e+2,x2+x5./2.0e+2,x3+x6./2.0e+2,F_ext1./1.06e+2+x4.*9.99999999990566e-1+u1.*(x7.*x9+x8.*x10).*2.794575471698113e-1,F_ext2./1.06e+2+x5.*9.99999999990566e-1-u1.*(x7.*x8-x9.*x10).*2.794575471698113e-1];
mt2 = [F_ext3./1.06e+2+x6.*9.99999999990566e-1+u1.*(t5-t6-t7+t8).*1.397287735849057e-1-4.905e-2,-t11.*t12.*(x7.*-4.0e+2+u2.*x8+u3.*x9+u4.*x10),t11.*t12.*(x8.*4.0e+2+u2.*x7-u3.*x10+u4.*x9),t11.*t12.*(x9.*4.0e+2+u3.*x7+u2.*x10-u4.*x8),t11.*t12.*(x10.*4.0e+2-u2.*x9+u3.*x8+u4.*x7)];
x_upd = reshape([mt1,mt2],10,1);
