function x_upd = quadcopter_df(in1,in2)
%QUADCOPTER_DF
%    X_UPD = QUADCOPTER_DF(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Sep-2021 20:30:06

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
x13 = in1(13,:);
t2 = x7.^2;
t3 = x8.^2;
t4 = x9.^2;
t5 = x10.^2;
t6 = x11.^2;
t7 = x12.^2;
t8 = x13.^2;
t9 = t2+t3+t4+t5;
t10 = t6+t7+t8+4.0e+4;
t11 = 1.0./sqrt(t9);
t12 = 1.0./sqrt(t10);
x_upd = [x1+x4./1.0e+2;x2+x5./1.0e+2;x3+x6./1.0e+2;x4+u1.*(x7.*x9+x8.*x10).*(2.0./5.3e+1);x5-u1.*(x7.*x8-x9.*x10).*(2.0./5.3e+1);x6+(u1.*(t2-t3-t4+t5))./5.3e+1-9.81e-2;-t11.*t12.*(x7.*-2.0e+2+x8.*x11+x9.*x12+x10.*x13);t11.*t12.*(x8.*2.0e+2+x7.*x11+x9.*x13-x10.*x12);t11.*t12.*(x9.*2.0e+2+x7.*x12-x8.*x13+x10.*x11);t11.*t12.*(x10.*2.0e+2+x7.*x13+x8.*x12-x9.*x11);u2.*1.0e+1+x11-(x12.*x13)./2.5e+2;u3.*(2.5e+1./4.0)+x12+(x11.*x13)./1.6e+2;u4.*5.0+x13-x11.*x12.*(3.0./1.0e+3)];
