function x_upd = quadcopter_act(in1,in2,in3)
%QUADCOPTER_ACT
%    X_UPD = QUADCOPTER_ACT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    12-Sep-2021 20:30:04

F_ext1 = in3(1,:);
F_ext2 = in3(2,:);
F_ext3 = in3(3,:);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
t2 = u2.^2;
t3 = u3.^2;
t4 = u4.^2;
t5 = x7.^2;
t6 = x8.^2;
t7 = x9.^2;
t8 = x10.^2;
t9 = t5+t6+t7+t8;
t10 = t2+t3+t4+4.0e+6;
t11 = 1.0./sqrt(t9);
t12 = 1.0./sqrt(t10);
x_upd = [x1+x4./1.0e+3;x2+x5./1.0e+3;x3+x6./1.0e+3;F_ext1./5.3e+2+x4.*9.999999999981132e-1+u1.*(x7.*x9+x8.*x10).*5.589150943396226e-2;F_ext2./5.3e+2+x5.*9.999999999981132e-1-u1.*(x7.*x8-x9.*x10).*5.589150943396226e-2;F_ext3./5.3e+2+x6.*9.999999999981132e-1+u1.*(t5-t6-t7+t8).*2.794575471698113e-2-9.81e-3;-t11.*t12.*(x7.*-2.0e+3+u2.*x8+u3.*x9+u4.*x10);t11.*t12.*(x8.*2.0e+3+u2.*x7-u3.*x10+u4.*x9);t11.*t12.*(x9.*2.0e+3+u3.*x7+u2.*x10-u4.*x8);t11.*t12.*(x10.*2.0e+3-u2.*x9+u3.*x8+u4.*x7)];
