function z_upd = error_upd(in1,in2,in3,in4)
%ERROR_UPD
%    Z_UPD = ERROR_UPD(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2022 16:31:31

p_bar1 = in3(1,:);
p_bar2 = in3(2,:);
p_bar3 = in3(3,:);
q_bar1 = in4(1,:);
q_bar2 = in4(2,:);
q_bar3 = in4(3,:);
q_bar4 = in4(4,:);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x7 = in2(7,:);
x8 = in2(8,:);
x9 = in2(9,:);
x10 = in2(10,:);
z1 = in1(1,:);
z2 = in1(2,:);
z3 = in1(3,:);
z4 = in1(4,:);
z5 = in1(5,:);
z6 = in1(6,:);
z7 = in1(7,:);
z_upd = [p_bar1.*(-1.0./2.0e+2)+x1./2.0e+2+z1;p_bar2.*(-1.0./2.0e+2)+x2./2.0e+2+z2;p_bar3.*(-1.0./2.0e+2)+x3./2.0e+2+z3;q_bar1.*(-1.0./2.0e+2)+x7./2.0e+2+z4;q_bar2.*(-1.0./2.0e+2)+x8./2.0e+2+z5;q_bar3.*(-1.0./2.0e+2)+x9./2.0e+2+z6;q_bar4.*(-1.0./2.0e+2)+x10./2.0e+2+z7];
