function Ad00 = Ad00(t)
%AD00
%    AD00 = AD00(T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Aug-2021 19:53:58

Ad00 = [1.0,t,t.^2,t.^3,t.^4,t.^5,t.^6,t.^7,t.^8,t.^9,t.^10,t.^11,t.^12,t.^13,t.^14];
