
classdef TrajTransferResponse < ros.Message
    %TrajTransferResponse MATLAB implementation of bridge_px4/TrajTransferResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'bridge_px4/TrajTransferResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '11ad27bbc0eb31f6209a5f0ff2f6788f' % The MD5 Checksum of the message definition
        PropertyList = { 'Checksum' } % List of non-constant message properties
        ROSPropertyList = { 'checksum' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Checksum
    end
    methods
        function set.Checksum(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TrajTransferResponse', 'Checksum');
            obj.Checksum = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.bridge_px4.TrajTransferResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.bridge_px4.TrajTransferResponse(strObj);
        end
    end
end
