function A = A_calc(in1,in2)
%A_CALC
%    A = A_CALC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Oct-2021 19:48:47

u1 = in2(1,:);
x3 = in1(3,:);
A = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,u1.*cos(x3).*(-1.0./5.3e+1),u1.*sin(x3).*(-1.0./5.3e+1),0.0,1.0./1.0e+2,0.0,0.0,1.0,0.0,0.0,0.0,1.0./1.0e+2,0.0,0.0,1.0,0.0,0.0,0.0,1.0./1.0e+2,0.0,0.0,1.0],[6,6]);
