function H2 = H2_calc(in1,in2)
%H2_CALC
%    H2 = H2_CALC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    21-Oct-2021 13:35:30

H2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
