function H3 = H3_calc(in1,in2)
%H3_CALC
%    H3 = H3_CALC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Oct-2021 16:01:41

H3 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
