function H3 = H3_calc(in1,in2)
%H3_CALC
%    H3 = H3_CALC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Oct-2021 23:39:48

H3 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
