function H6 = H6_calc(in1,in2)
%H6_CALC
%    H6 = H6_CALC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Oct-2021 23:39:49

H6 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
