// Generated by gencpp from file bridge_px4/TrajTransferResponse.msg
// DO NOT EDIT!


#ifndef BRIDGE_PX4_MESSAGE_TRAJTRANSFERRESPONSE_H
#define BRIDGE_PX4_MESSAGE_TRAJTRANSFERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bridge_px4
{
template <class ContainerAllocator>
struct TrajTransferResponse_
{
  typedef TrajTransferResponse_<ContainerAllocator> Type;

  TrajTransferResponse_()
    : checksum(false)  {
    }
  TrajTransferResponse_(const ContainerAllocator& _alloc)
    : checksum(false)  {
  (void)_alloc;
    }



   typedef uint8_t _checksum_type;
  _checksum_type checksum;





  typedef boost::shared_ptr< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TrajTransferResponse_

typedef ::bridge_px4::TrajTransferResponse_<std::allocator<void> > TrajTransferResponse;

typedef boost::shared_ptr< ::bridge_px4::TrajTransferResponse > TrajTransferResponsePtr;
typedef boost::shared_ptr< ::bridge_px4::TrajTransferResponse const> TrajTransferResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bridge_px4::TrajTransferResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bridge_px4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11ad27bbc0eb31f6209a5f0ff2f6788f";
  }

  static const char* value(const ::bridge_px4::TrajTransferResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11ad27bbc0eb31f6ULL;
  static const uint64_t static_value2 = 0x209a5f0ff2f6788fULL;
};

template<class ContainerAllocator>
struct DataType< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bridge_px4/TrajTransferResponse";
  }

  static const char* value(const ::bridge_px4::TrajTransferResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool checksum\n"
;
  }

  static const char* value(const ::bridge_px4::TrajTransferResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrajTransferResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bridge_px4::TrajTransferResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bridge_px4::TrajTransferResponse_<ContainerAllocator>& v)
  {
    s << indent << "checksum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRIDGE_PX4_MESSAGE_TRAJTRANSFERRESPONSE_H
