function w_dot = ang_acc_est(q_w,q_x,q_y,q_z,tau_ext_x,tau_ext_y,tau_ext_z,u1,u2,u3,u4,v_x,v_y,v_z,w_x,w_y,w_z)
%ANG_ACC_EST
%    W_DOT = ANG_ACC_EST(Q_W,Q_X,Q_Y,Q_Z,TAU_EXT_X,TAU_EXT_Y,TAU_EXT_Z,U1,U2,U3,U4,V_X,V_Y,V_Z,W_X,W_Y,W_Z)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-May-2021 17:49:43

t2 = q_w.^2;
t3 = q_x.^2;
t4 = q_y.^2;
t5 = q_z.^2;
t6 = u1.^2;
t7 = u2.^2;
t8 = u3.^2;
t9 = u4.^2;
t10 = t6.*5.084612337662338e-7;
t11 = t7.*5.084612337662338e-7;
t12 = t8.*5.084612337662338e-7;
t13 = t9.*5.084612337662338e-7;
t14 = -t10;
w_dot = [t11+t12-t13+t14+tau_ext_x.*6.493506493506494e+2-w_x./1.54e+6-(t2.*v_x)./1.54e+6-(t3.*v_x)./1.54e+6+(t4.*v_x)./1.54e+6+(t5.*v_x)./1.54e+6-w_y.*w_z.*(9.7e+1./1.54e+2)+(q_w.*q_y.*v_z)./7.7e+5-(q_w.*q_z.*v_y)./7.7e+5-(q_x.*q_y.*v_y)./7.7e+5-(q_x.*q_z.*v_z)./7.7e+5;t11-t12+t13+t14+tau_ext_y.*6.493506493506494e+2-w_y./1.54e+6-(t2.*v_y)./1.54e+6+(t3.*v_y)./1.54e+6-(t4.*v_y)./1.54e+6+(t5.*v_y)./1.54e+6+w_x.*w_z.*(9.7e+1./1.54e+2)-(q_w.*q_x.*v_z)./7.7e+5+(q_w.*q_z.*v_x)./7.7e+5-(q_x.*q_y.*v_x)./7.7e+5-(q_y.*q_z.*v_z)./7.7e+5;t6.*(-3.525019920318725e-7)-t7.*3.525019920318725e-7+t8.*3.525019920318725e-7+t9.*3.525019920318725e-7+tau_ext_z.*3.98406374501992e+2-w_z./2.51e+6-(t2.*v_z)./2.51e+6+(t3.*v_z)./2.51e+6+(t4.*v_z)./2.51e+6-(t5.*v_z)./2.51e+6+(q_w.*q_x.*v_y)./1.255e+6-(q_w.*q_y.*v_x)./1.255e+6-(q_x.*q_z.*v_x)./1.255e+6-(q_y.*q_z.*v_y)./1.255e+6];
