function v_dot = lin_acc_est(F_ext_x,F_ext_y,F_ext_z,q_w,q_x,q_y,q_z,u1,u2,u3,u4)
%LIN_ACC_EST
%    V_DOT = LIN_ACC_EST(F_EXT_X,F_EXT_Y,F_EXT_Z,Q_W,Q_X,Q_Y,Q_Z,U1,U2,U3,U4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Mar-2021 16:14:18

t2 = u1.^2;
t3 = u2.^2;
t4 = u3.^2;
t5 = u4.^2;
t6 = t2+t3+t4+t5;
v_dot = [F_ext_x.*(2.0e+1./1.3e+1)+t6.*(q_w.*q_y+q_x.*q_z).*2.7224e-8;F_ext_y.*(2.0e+1./1.3e+1)-t6.*(q_w.*q_x-q_y.*q_z).*2.7224e-8;F_ext_z.*(2.0e+1./1.3e+1)+t6.*(q_w.^2-q_x.^2-q_y.^2+q_z.^2).*1.3612e-8-9.81e+2./1.0e+2];
