function v_dot = lin_acc_act(F_ext_x,F_ext_y,F_ext_z,q_w,q_x,q_y,q_z,u1,u2,u3,u4,v_x,v_y,v_z)
%LIN_ACC_ACT
%    V_DOT = LIN_ACC_ACT(F_EXT_X,F_EXT_Y,F_EXT_Z,Q_W,Q_X,Q_Y,Q_Z,U1,U2,U3,U4,V_X,V_Y,V_Z)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Feb-2021 14:26:14

t2 = q_w.*q_x;
t3 = q_w.*q_y;
t4 = q_w.*q_z;
t5 = q_x.*q_y;
t6 = q_x.*q_z;
t7 = q_y.*q_z;
t8 = q_w.^2;
t9 = q_x.^2;
t10 = q_y.^2;
t11 = q_z.^2;
t12 = u1.^2;
t13 = u2.^2;
t14 = u3.^2;
t15 = u4.^2;
t16 = t8./2.0;
t17 = t9./2.0;
t18 = t10./2.0;
t19 = t11./2.0;
t21 = t12+t13+t14+t15;
t20 = -t19;
v_dot = [F_ext_x.*(2.0e+1./1.3e+1)+t21.*(t3+t6).*2.7224e-8-v_x.*(t16+t17-t18+t20).*(2.0e+1./1.3e+1)+v_y.*(t4-t5).*(2.0e+1./1.3e+1)-v_z.*(t3./5.0+t6./5.0).*(2.0e+1./1.3e+1);F_ext_y.*(2.0e+1./1.3e+1)-v_x.*(t4+t5).*(2.0e+1./1.3e+1)-v_y.*(t16-t17+t18+t20).*(2.0e+1./1.3e+1)-t21.*(t2-t7).*2.7224e-8+v_z.*(t2./5.0-t7./5.0).*(2.0e+1./1.3e+1);F_ext_z.*(2.0e+1./1.3e+1)-v_y.*(t2+t7).*(2.0e+1./1.3e+1)+v_x.*(t3-t6).*(2.0e+1./1.3e+1)-v_z.*(t8./1.0e+1-t9./1.0e+1-t10./1.0e+1+t11./1.0e+1).*(2.0e+1./1.3e+1)+t21.*(t8-t9-t10+t11).*1.3612e-8-9.81e+2./1.0e+2];
